#!/usr/bin/env node
/**
 * tramito.mjs — Tramito JSON→BPMN local conversion CLI (companion tool for the skill)
 *
 * Everything runs locally and fully offline: validation and layout are powered by the
 * bundled engine in ./engine.mjs (tramito-layout + elkjs + bpmn-moddle, generated by
 * tools/build-engine.mjs). No account, no API key, no quota, no network, no npm at
 * runtime — the skill zip is self-contained, which sandboxed hosts (e.g. ChatGPT
 * skills) require. Process data never leaves the machine.
 *
 * The engine version is pinned at build time; upgrading it means re-running
 * tools/build-engine.mjs and cutting a new skill release.
 *
 * Usage:
 *   node tramito.mjs validate <graph.json>              structural validation (local, unlimited, writes nothing)
 *   node tramito.mjs render <graph.json> [--out DIR] [--name NAME]
 *                                                        convert: writes NAME.bpmn + NAME.graph.json
 *   node tramito.mjs doctor                              environment self-check (runtime / engine / compile smoke)
 *   node tramito.mjs --version | --help
 *
 * Error layering (mirrors the tramito-layout compiler contract):
 *   - Validation errors (issues / AggregateError) → problems with the input graph;
 *     fix them per the hints and retry.
 *   - InternalCompilerError (code=internal_compiler_error) → a bug in the compiler itself.
 *     Do NOT keep tweaking the graph; report it upstream with the stage and the graph.
 *
 * Exit codes: 0 success; 1 conversion failed (validation error or compiler bug);
 * 2 usage or local-environment error. stdout carries result JSON; errors go to stderr.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  validateFlat,
  formatIssuesForFeedback,
  layoutBpmnFlat,
  warmupLayoutEngine,
  InternalCompilerError,
  ENGINE_VERSION,
} from './engine.mjs';

/* ────────────── Args & file helpers (semantics carried over from the v1 CLI) ────────────── */

const VALUE_OPTS = new Set(['--out', '--name']);

/** Parse argv: returns { positionals: string[], opts: Map<string,string> }. */
function parseArgs(args) {
  const positionals = [];
  const opts = new Map();
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--') {
      positionals.push(...args.slice(i + 1));
      break;
    }
    if (a.startsWith('--')) {
      if (!VALUE_OPTS.has(a)) fail(`Unknown option: ${a} (available: ${[...VALUE_OPTS].join(' ')})`);
      const v = args[i + 1];
      if (v === undefined || v.startsWith('--')) fail(`Option ${a} requires a value`);
      opts.set(a, v);
      i++;
    } else {
      positionals.push(a);
    }
  }
  return { positionals, opts };
}

/** Sanitize output file names: strip control chars / path separators / collapse whitespace. */
function sanitizeName(raw) {
  const cleaned = String(raw)
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1f\x7f]/g, '')
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned || 'diagram';
}

/** Derive the default output name from the input file: foo.graph.json → foo (not foo.graph). */
function defaultNameFor(file) {
  return sanitizeName(path.basename(file, path.extname(file)).replace(/\.graph$/i, ''));
}

/** Never silently overwrite: allocate one shared version suffix for a (dir, name, exts) family — both files keep the same stem. */
function nonClobberingFamily(dir, name, exts) {
  for (let v = 1; ; v++) {
    const stem = v === 1 ? name : `${name}-v${v}`;
    const paths = exts.map((ext) => path.join(dir, `${stem}.${ext}`));
    if (paths.every((p) => !fs.existsSync(p))) return paths;
  }
}

function readGraphFile(file) {
  if (!fs.existsSync(file)) fail(`File not found: ${file}`);
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
  } catch (e) {
    fail(`Graph file is not valid JSON: ${e.message}`);
  }
}

function skillVersion() {
  try {
    return JSON.parse(fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'package.json'), 'utf-8')).version;
  } catch {
    return 'unknown';
  }
}

/* ────────────── Commands ────────────── */

async function cmdValidate(positionals) {
  const graphFile = positionals[0];
  if (!graphFile) fail('Usage: tramito.mjs validate <graph.json>');
  const graph = readGraphFile(graphFile);
  const issues = validateFlat(graph);
  const valid = !issues.some((i) => i.severity === 'error');
  const out = { ok: valid, valid, issueCount: issues.length, issues };
  if (issues.length > 0) out.feedback = formatIssuesForFeedback(issues);
  console.log(JSON.stringify(out, null, 2));
  process.exitCode = valid ? 0 : 1;
}

/** ICE exit path: a compiler bug is not the input's fault — point to reporting, not to graph edits. */
function reportIce(e) {
  console.error(JSON.stringify({
    ok: false,
    error: {
      code: 'internal_compiler_error',
      stage: e.stage ?? null,
      message: e.message,
      report: ISSUE_REPO,
      note: `This is a bug in tramito-layout (the input already passed validation). Do not keep retrying with graph edits; please report the stage, the graph file and the full error at ${ISSUE_REPO}.`,
    },
  }, null, 2));
  process.exit(1);
}

async function cmdRender(positionals, opts) {
  const graphFile = positionals[0];
  if (!graphFile) fail('Usage: tramito.mjs render <graph.json> [--out DIR] [--name NAME]');
  const graph = readGraphFile(graphFile);
  const outDir = opts.get('--out') || '.';
  const name = sanitizeName(opts.get('--name') || defaultNameFor(graphFile));

  const issues = validateFlat(graph);
  if (issues.some((i) => i.severity === 'error')) {
    console.error(JSON.stringify({
      ok: false,
      error: {
        code: 'graph_invalid',
        message: 'Structural validation failed; no files were written. Fix the graph per the issue hints and retry.',
        issueCount: issues.length,
        issues,
        feedback: formatIssuesForFeedback(issues),
      },
    }, null, 2));
    process.exit(1);
  }

  const t0 = Date.now();
  let xml;
  try {
    ({ xml } = await layoutBpmnFlat(graph, name));
  } catch (e) {
    if (e instanceof InternalCompilerError) reportIce(e);
    if (e instanceof AggregateError) {
      // Normally caught by validateFlat above; reaching here means validation and
      // conversion disagreed — surface every sub-error verbatim.
      console.error(JSON.stringify({
        ok: false,
        error: {
          code: 'graph_invalid',
          message: 'Structural problems found during conversion (these should have surfaced in validation — unexpected path):',
          issues: e.errors.map((x) => x.message),
        },
      }, null, 2));
      process.exit(1);
    }
    throw e;
  }

  fs.mkdirSync(outDir, { recursive: true });
  const [bpmnPath, graphPath] = nonClobberingFamily(outDir, name, ['bpmn', 'graph.json']);
  fs.writeFileSync(bpmnPath, xml, 'utf-8');
  fs.writeFileSync(graphPath, JSON.stringify(graph, null, 2), 'utf-8');

  const warnings = issues.filter((i) => i.severity !== 'error');
  console.log(JSON.stringify({
    ok: true,
    files: { bpmn: bpmnPath, graph: graphPath },
    ms: Date.now() - t0,
    ...(warnings.length > 0 ? { warnings } : {}),
  }, null, 2));
}

async function cmdDoctor() {
  const runtime = isBunRuntime() ? `bun ${process.versions.bun}` : `node ${process.versions.node}`;

  const t0 = Date.now();
  await warmupLayoutEngine();
  const warmupMs = Date.now() - t0;

  // Minimal viable graph smoke test: 3 nodes, 2 edges, runs the full layout+serialization pipeline
  const smoke = {
    nodes: [
      { id: 's', type: 'startEvent' },
      { id: 't', type: 'userTask', name: 'smoke' },
      { id: 'e', type: 'endEvent' },
    ],
    edges: [
      { id: 'f1', source: 's', target: 't' },
      { id: 'f2', source: 't', target: 'e' },
    ],
  };
  const t1 = Date.now();
  try {
    const { xml } = await layoutBpmnFlat(smoke, 'doctor');
    console.log(JSON.stringify({
      ok: true,
      runtime,
      skillVersion: skillVersion(),
      engine: {
        name: 'tramito-layout (bundled)',
        version: ENGINE_VERSION,
        warmupMs,
        smokeMs: Date.now() - t1,
        smokeBytes: xml.length,
      },
    }, null, 2));
  } catch (e) {
    if (e instanceof InternalCompilerError) reportIce(e);
    throw e;
  }
}

/* ────────────── Entry point ────────────── */

const ISSUE_REPO = 'https://github.com/LcpMarvel/tramito-layout/issues';
const isBunRuntime = () => Boolean(process.versions.bun);

function fail(message) {
  console.error(JSON.stringify({ ok: false, error: { code: 'cli_error', message } }, null, 2));
  process.exit(2);
}

const HELP = `tramito.mjs — Tramito JSON→BPMN local conversion CLI (v${skillVersion()})

Usage:
  node tramito.mjs validate <graph.json>              structural validation (local, unlimited, writes nothing)
  node tramito.mjs render <graph.json> [--out DIR] [--name NAME]
                                                      convert: writes NAME.bpmn + NAME.graph.json
  node tramito.mjs doctor                             environment self-check (runtime / engine / compile smoke)
  node tramito.mjs --version

Notes: fully offline and self-contained — the tramito-layout engine is bundled next to
this script; nothing is installed or downloaded at runtime.
Exit codes: 0 success; 1 conversion failed (validation error or compiler bug);
2 usage or local-environment error.`;

async function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  if (cmd === '--help' || cmd === '-h') {
    console.log(HELP);
    return;
  }
  if (cmd === '--version') {
    console.log(skillVersion());
    return;
  }
  if (!cmd || !['validate', 'render', 'doctor'].includes(cmd)) {
    fail(`Unknown command: ${cmd || '(empty)'}. Available: validate | render | doctor (see --help for full usage)`);
  }
  const { positionals, opts } = parseArgs(rest);
  if (cmd === 'doctor') return await cmdDoctor();
  if (cmd === 'validate') return await cmdValidate(positionals);
  return await cmdRender(positionals, opts);
}

main().catch((e) => {
  console.error(JSON.stringify({
    ok: false,
    error: { code: String(e.code || 'unexpected_error'), message: e?.stack || String(e) },
  }, null, 2));
  process.exit(1);
});
