#!/usr/bin/env node
/**
 * tramito.mjs — Tramito JSON→BPMN local conversion CLI (companion tool for the skill)
 *
 * One CLI, two distribution flavors, auto-detected at load time:
 *
 *   1. Bundled (OpenAI plugin zip): the engine sits next to this script in
 *      ./engine.mjs (tramito-layout + elkjs + bpmn-moddle, generated by
 *      tools/build-engine.mjs). Fully offline — required by sandboxed hosts that
 *      forbid runtime installs.
 *   2. npm-bootstrap (WorkBuddy / slim zip): engine.mjs is NOT shipped. On first
 *      run the CLI installs tramito-layout (spec from package.json, e.g. ~2.8.1)
 *      via npm/bun into this skill directory, then imports it. Keeps the zip
 *      tiny (KBs instead of MBs); needs network once.
 *
 * No account, no API key, no quota, no telemetry in either flavor; process data
 * never leaves the machine.
 *
 * Usage:
 *   node tramito.mjs validate <graph.json>              structural validation (local, unlimited, writes nothing)
 *   node tramito.mjs render <graph.json> [--out DIR] [--name NAME]
 *                                                        convert: writes NAME.bpmn + NAME.graph.json
 *   node tramito.mjs doctor                              environment self-check (runtime / engine / compile smoke)
 *   node tramito.mjs --version | --help
 *
 * Error layering (mirrors the tramito-layout compiler contract):
 *   - Validation errors (issues / AggregateError) → problems with the input graph;
 *     fix them per the hints and retry.
 *   - InternalCompilerError (code=internal_compiler_error) → a bug in the compiler itself.
 *     Do NOT keep tweaking the graph; report it upstream with the stage and the graph.
 *
 * Exit codes: 0 success; 1 conversion failed (validation error or compiler bug);
 * 2 usage or local-environment error. stdout carries result JSON; errors go to stderr.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SKILL_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ENGINE_FILE = path.join(SKILL_ROOT, 'scripts', 'engine.mjs');
const DEPS_MARKER = path.join(SKILL_ROOT, 'node_modules', 'tramito-layout', 'package.json');
const LOCK_DIR = path.join(SKILL_ROOT, '.install-lock');
const LOCK_STALE_MS = 5 * 60_000; // stale-lock takeover threshold: installs normally finish in seconds
const ISSUE_REPO = 'https://github.com/LcpMarvel/tramito-layout/issues';

/* ────────────── Args & file helpers (semantics carried over from the v1 CLI) ────────────── */

const VALUE_OPTS = new Set(['--out', '--name']);

/** Parse argv: returns { positionals: string[], opts: Map<string,string> }. */
function parseArgs(args) {
  const positionals = [];
  const opts = new Map();
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--') {
      positionals.push(...args.slice(i + 1));
      break;
    }
    if (a.startsWith('--')) {
      if (!VALUE_OPTS.has(a)) fail(`Unknown option: ${a} (available: ${[...VALUE_OPTS].join(' ')})`);
      const v = args[i + 1];
      if (v === undefined || v.startsWith('--')) fail(`Option ${a} requires a value`);
      opts.set(a, v);
      i++;
    } else {
      positionals.push(a);
    }
  }
  return { positionals, opts };
}

/** Sanitize output file names: strip control chars / path separators / collapse whitespace. */
function sanitizeName(raw) {
  const cleaned = String(raw)
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1f\x7f]/g, '')
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned || 'diagram';
}

/** Derive the default output name from the input file: foo.graph.json → foo (not foo.graph). */
function defaultNameFor(file) {
  return sanitizeName(path.basename(file, path.extname(file)).replace(/\.graph$/i, ''));
}

/** Never silently overwrite: allocate one shared version suffix for a (dir, name, exts) family — both files keep the same stem. */
function nonClobberingFamily(dir, name, exts) {
  for (let v = 1; ; v++) {
    const stem = v === 1 ? name : `${name}-v${v}`;
    const paths = exts.map((ext) => path.join(dir, `${stem}.${ext}`));
    if (paths.every((p) => !fs.existsSync(p))) return paths;
  }
}

function readGraphFile(file) {
  if (!fs.existsSync(file)) fail(`File not found: ${file}`);
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
  } catch (e) {
    fail(`Graph file is not valid JSON: ${e.message}`);
  }
}

function skillVersion() {
  try {
    return JSON.parse(fs.readFileSync(path.join(SKILL_ROOT, 'package.json'), 'utf-8')).version;
  } catch {
    return 'unknown';
  }
}

/** npm 版本规格（单一来源：package.json 的 dependencies；bundle 版无需它）。 */
function engineSpec() {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(SKILL_ROOT, 'package.json'), 'utf-8'));
    const spec = pkg.dependencies && pkg.dependencies['tramito-layout'];
    if (typeof spec === 'string' && spec.length > 0) return spec;
  } catch { /* fall through */ }
  return '~2.8.1';
}

/* ────────────── npm bootstrap (slim flavor only; skipped when engine.mjs is bundled) ────────────── */

const sleep = (ms) => new Promise((res) => setTimeout(res, ms));
const isBunRuntime = () => Boolean(process.versions.bun);

function isModuleNotFound(e) {
  return Boolean(e && (e.code === 'ERR_MODULE_NOT_FOUND' || e.code === 'MODULE_NOT_FOUND'));
}

/** Fail fast if the skill dir is unwritable — node_modules must land there, don't let npm run for nothing. */
function assertWritable(dir) {
  const probe = path.join(dir, `.write-probe-${process.pid}`);
  try {
    fs.writeFileSync(probe, '');
    fs.rmSync(probe, { force: true });
  } catch (e) {
    fail(`Skill directory is not writable (${dir}): cannot install the engine. Run this manually: cd "${dir}" && npm install --omit=dev — or use the bundled flavor of the skill. (${e.message})`);
  }
}

function tryAcquireLock() {
  try {
    fs.mkdirSync(LOCK_DIR);
    return true;
  } catch (e) {
    if (e.code === 'EEXIST') return false;
    throw e;
  }
}

function releaseLock() {
  fs.rmSync(LOCK_DIR, { recursive: true, force: true });
}

function hasBin(cmd) {
  return spawnSync(cmd, ['--version'], { stdio: 'ignore' }).status === 0;
}

function installedEngineVersion() {
  try {
    return JSON.parse(fs.readFileSync(DEPS_MARKER, 'utf-8')).version;
  } catch {
    return null;
  }
}

/** Install the engine per package.json spec. The install lock is held by the caller. */
function runInstaller() {
  const spec = engineSpec();
  const npmBin = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  if (hasBin(npmBin)) {
    const r = spawnSync(npmBin, ['install', '--omit=dev', '--no-audit', '--no-fund', '--prefer-online'], { cwd: SKILL_ROOT, stdio: 'inherit' });
    if (r.status !== 0) {
      fail(`Engine install failed (npm install exited with ${r.status}). Manual command: cd "${SKILL_ROOT}" && npm install --omit=dev. For offline/proxied environments, make sure npm works first.`);
    }
    return;
  }
  if (hasBin('bun')) {
    const r = spawnSync('bun', ['install', '--production'], { cwd: SKILL_ROOT, stdio: 'inherit' });
    if (r.status !== 0) {
      fail(`Engine install failed (bun install exited with ${r.status}). Manual command: cd "${SKILL_ROOT}" && bun install --production`);
    }
    return;
  }
  fail(`Neither npm nor bun found on this machine. Install the engine manually: cd "${SKILL_ROOT}" && npm install --omit=dev (or install Node.js ≥ 20 first).`);
}

/**
 * Make sure node_modules is ready: the process that wins the lock installs,
 * the others wait for it; after LOCK_STALE_MS a lock is considered stale and taken over.
 */
async function ensureDeps() {
  if (fs.existsSync(DEPS_MARKER)) return; // already installed — silent fast path
  if (!isBunRuntime() && Number(process.versions.node.split('.')[0]) < 20) {
    fail(`Runtime too old: Node.js ≥ 20 or Bun ≥ 1.3 required (currently ${isBunRuntime() ? 'bun' : 'node'} ${process.versions.bun || process.versions.node}).`);
  }
  assertWritable(SKILL_ROOT);
  const spec = engineSpec();
  console.error(`First run: installing the layout engine (tramito-layout@${spec}; one time only, needs network)… Directory: ${SKILL_ROOT}`);
  const started = Date.now();
  for (;;) {
    if (fs.existsSync(DEPS_MARKER)) return; // another process already installed
    if (tryAcquireLock()) {
      try {
        if (fs.existsSync(DEPS_MARKER)) return; // double-check: someone finished while we waited
        runInstaller();
        if (!fs.existsSync(DEPS_MARKER)) fail('The install command finished but tramito-layout is still missing — check the installer output above.');
        console.error('Engine installed.');
        return;
      } finally {
        releaseLock();
      }
    }
    if (Date.now() - started > LOCK_STALE_MS) {
      console.error('Waited over 5 minutes for the install lock; treating it as stale and taking over.');
      releaseLock();
      continue;
    }
    await sleep(1000);
  }
}

/* ────────────── Engine loader: bundled first, npm bootstrap as fallback ────────────── */

let enginePromise = null;
let engineSource = '';
let engineVersionValue = null;

function loadEngine() {
  if (!enginePromise) {
    enginePromise = (async () => {
      // 1) Bundled flavor (OpenAI zip): engine.mjs next to this script, fully offline.
      if (fs.existsSync(ENGINE_FILE)) {
        const m = await import('./engine.mjs');
        engineSource = 'bundled';
        engineVersionValue = m.ENGINE_VERSION ?? null;
        return m;
      }
      // 2) Slim flavor (WorkBuddy zip): install per package.json spec on first run.
      await ensureDeps();
      const m = await import('tramito-layout');
      engineSource = `npm (${engineSpec()})`;
      engineVersionValue = installedEngineVersion();
      return m;
    })();
  }
  return enginePromise;
}

/* ────────────── Commands ────────────── */

async function cmdValidate(positionals) {
  const graphFile = positionals[0];
  if (!graphFile) fail('Usage: tramito.mjs validate <graph.json>');
  const graph = readGraphFile(graphFile);
  const { validateFlat, formatIssuesForFeedback } = await loadEngine();
  const issues = validateFlat(graph);
  const valid = !issues.some((i) => i.severity === 'error');
  const out = { ok: valid, valid, issueCount: issues.length, issues };
  if (issues.length > 0) out.feedback = formatIssuesForFeedback(issues);
  console.log(JSON.stringify(out, null, 2));
  process.exitCode = valid ? 0 : 1;
}

/** ICE exit path: a compiler bug is not the input's fault — point to reporting, not to graph edits. */
function reportIce(e) {
  console.error(JSON.stringify({
    ok: false,
    error: {
      code: 'internal_compiler_error',
      stage: e.stage ?? null,
      message: e.message,
      report: ISSUE_REPO,
      note: `This is a bug in tramito-layout (the input already passed validation). Do not keep retrying with graph edits; please report the stage, the graph file and the full error at ${ISSUE_REPO}.`,
    },
  }, null, 2));
  process.exit(1);
}

async function cmdRender(positionals, opts) {
  const graphFile = positionals[0];
  if (!graphFile) fail('Usage: tramito.mjs render <graph.json> [--out DIR] [--name NAME]');
  const graph = readGraphFile(graphFile);
  const outDir = opts.get('--out') || '.';
  const name = sanitizeName(opts.get('--name') || defaultNameFor(graphFile));

  const { validateFlat, formatIssuesForFeedback, layoutBpmnFlat, InternalCompilerError } = await loadEngine();
  const issues = validateFlat(graph);
  if (issues.some((i) => i.severity === 'error')) {
    console.error(JSON.stringify({
      ok: false,
      error: {
        code: 'graph_invalid',
        message: 'Structural validation failed; no files were written. Fix the graph per the issue hints and retry.',
        issueCount: issues.length,
        issues,
        feedback: formatIssuesForFeedback(issues),
      },
    }, null, 2));
    process.exit(1);
  }

  const t0 = Date.now();
  let xml;
  try {
    ({ xml } = await layoutBpmnFlat(graph, name));
  } catch (e) {
    if (e instanceof InternalCompilerError) reportIce(e);
    if (e instanceof AggregateError) {
      // Normally caught by validateFlat above; reaching here means validation and
      // conversion disagreed — surface every sub-error verbatim.
      console.error(JSON.stringify({
        ok: false,
        error: {
          code: 'graph_invalid',
          message: 'Structural problems found during conversion (these should have surfaced in validation — unexpected path):',
          issues: e.errors.map((x) => x.message),
        },
      }, null, 2));
      process.exit(1);
    }
    throw e;
  }

  fs.mkdirSync(outDir, { recursive: true });
  const [bpmnPath, graphPath] = nonClobberingFamily(outDir, name, ['bpmn', 'graph.json']);
  fs.writeFileSync(bpmnPath, xml, 'utf-8');
  fs.writeFileSync(graphPath, JSON.stringify(graph, null, 2), 'utf-8');

  const warnings = issues.filter((i) => i.severity !== 'error');
  console.log(JSON.stringify({
    ok: true,
    files: { bpmn: bpmnPath, graph: graphPath },
    ms: Date.now() - t0,
    ...(warnings.length > 0 ? { warnings } : {}),
  }, null, 2));
}

async function cmdDoctor() {
  const runtime = isBunRuntime() ? `bun ${process.versions.bun}` : `node ${process.versions.node}`;
  const { warmupLayoutEngine, layoutBpmnFlat, InternalCompilerError } = await loadEngine();

  const t0 = Date.now();
  await warmupLayoutEngine();
  const warmupMs = Date.now() - t0;

  // Minimal viable graph smoke test: 3 nodes, 2 edges, runs the full layout+serialization pipeline
  const smoke = {
    nodes: [
      { id: 's', type: 'startEvent' },
      { id: 't', type: 'userTask', name: 'smoke' },
      { id: 'e', type: 'endEvent' },
    ],
    edges: [
      { id: 'f1', source: 's', target: 't' },
      { id: 'f2', source: 't', target: 'e' },
    ],
  };
  const t1 = Date.now();
  try {
    const { xml } = await layoutBpmnFlat(smoke, 'doctor');
    console.log(JSON.stringify({
      ok: true,
      runtime,
      skillVersion: skillVersion(),
      engine: {
        name: 'tramito-layout',
        source: engineSource,
        version: engineVersionValue,
        warmupMs,
        smokeMs: Date.now() - t1,
        smokeBytes: xml.length,
      },
    }, null, 2));
  } catch (e) {
    if (e instanceof InternalCompilerError) reportIce(e);
    throw e;
  }
}

/* ────────────── Entry point ────────────── */

function fail(message) {
  console.error(JSON.stringify({ ok: false, error: { code: 'cli_error', message } }, null, 2));
  process.exit(2);
}

const HELP = `tramito.mjs — Tramito JSON→BPMN local conversion CLI (v${skillVersion()})

Usage:
  node tramito.mjs validate <graph.json>              structural validation (local, unlimited, writes nothing)
  node tramito.mjs render <graph.json> [--out DIR] [--name NAME]
                                                      convert: writes NAME.bpmn + NAME.graph.json
  node tramito.mjs doctor                             environment self-check (runtime / engine / compile smoke)
  node tramito.mjs --version

Notes: the engine is either bundled next to this script (offline flavor) or
installed automatically on first run per package.json (npm flavor, network once).
Exit codes: 0 success; 1 conversion failed (validation error or compiler bug);
2 usage or local-environment error.`;

async function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  if (cmd === '--help' || cmd === '-h') {
    console.log(HELP);
    return;
  }
  if (cmd === '--version') {
    console.log(skillVersion());
    return;
  }
  if (!cmd || !['validate', 'render', 'doctor'].includes(cmd)) {
    fail(`Unknown command: ${cmd || '(empty)'}. Available: validate | render | doctor (see --help for full usage)`);
  }
  const { positionals, opts } = parseArgs(rest);
  if (cmd === 'doctor') return await cmdDoctor();
  if (cmd === 'validate') return await cmdValidate(positionals);
  return await cmdRender(positionals, opts);
}

main().catch((e) => {
  console.error(JSON.stringify({
    ok: false,
    error: { code: String(e.code || 'unexpected_error'), message: e?.stack || String(e) },
  }, null, 2));
  process.exit(1);
});
